name: t3_formosa
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  binary: ^3.0.1 
  quiver: ^3.2.1
  unorm_dart: ^0.3.0
  test: ^1.24.0
  crypto: ^3.0.5

dev_dependencies:
  lints: ^3.0.0
