name: t3_formosa
description: Improvement upon bip39 to provide a semantically connected words.
version: 0.1.0-dev
publish_to: none

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  binary: ^3.0.1 
  quiver: ^3.2.1
  unorm_dart: ^0.3.0
  test: ^1.24.0
  crypto: ^3.0.5
  t3_crypto_objects:
    git:
      url: git@github.com:T3-InfoSec/t3-crypto-objects-dart.git
      ref: initialise_objects

dev_dependencies:
  lints: ^3.0.0
