name: mnemonic
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  binary: ^3.0.1
  flutter_test:
    sdk: flutter
  quiver: ^3.2.1
  unorm_dart: ^0.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
